-- Залишки й ціни для сайту. Валерію: напиши запит під свою базу УкрСкладу.
--
-- Запит лише читає. Колонки мають називатися саме так:
--   ID     — ID товару (той самий, що TOVAR_NAME.NUM і TOVAR_ID у рядках видаткової)
--   SKU    — артикул (поле «Код»)
--   SIZE   — розмір
--   NAME   — повна назва
--   QTY    — скільки зараз є на складі
--   PRICE  — роздрібна ціна
--   SALE   — «Ціна Акція» (0 або NULL — без акції); колонку можна не додавати
--
-- {SKLAD_ID} програма підставить сама — число з [ukrsklad] sklad_id.
-- Товари з нулем теж потрібні: так сайт знає, що їх уже немає.
-- SKU, SIZE і NAME сайт бере лише для нового товару, щоб завести картку.
--
-- Якщо назва падає з «Cannot transliterate character between character sets» —
-- поле в базі в іншому кодуванні. Тоді віддайте його сирими байтами, програма
-- сама розпізнає UTF-8 чи WIN1251:
--   CAST(t.NAME AS VARCHAR(1000) CHARACTER SET OCTETS) AS NAME
-- Так само можна з SKU і SIZE.
--
-- Приклад (назви таблиць і полів — перевір):
--
-- SELECT t.NUM      AS ID,
--        t.KOD      AS SKU,
--        t.RAZMER   AS SIZE,
--        CAST(t.NAME AS VARCHAR(1000) CHARACTER SET OCTETS) AS NAME,
--        z.KOLVO    AS QTY,
--        t.CENA_R   AS PRICE,
--        t.CENA_AKC AS SALE
--   FROM TOVAR_NAME t
--   LEFT JOIN TOVAR_ZAL z ON z.TOVAR_ID = t.NUM AND z.SKLAD_ID = {SKLAD_ID}
