-- ============================================================
--  БРОНЮВАННЯ НОМЕРІВ — рушій для сайтів-готелів платформи
--
--  Після цього файлу для кожного сайту-готелю виконується ще один —
--  db/tg-filin.sql: він не дає стукати в бота, поки не підключено
--  жодного чату, і видає код запрошення.
--
--  Виконати ОДИН раз у Supabase → SQL Editor. Повторний запуск
--  безпечний: таблиці створюються через "if not exists",
--  функції переписуються.
--
--  Як це працює:
--    1. Типи номерів лежать у звичайній колекції items
--       (collection = 'rooms'): назва, місткість, ЦІНА і головне —
--       extra.units, скільки таких номерів є фізично.
--    2. Сайт перед показом календаря питає booking_busy() —
--       вона віддає дати, на які вільних номерів цього типу
--       вже не лишилось.
--    3. Гість натискає «Надіслати заявку» → place_booking().
--       Вона ще раз перевіряє вільні місця (за секунду до того
--       хтось міг забрати останній номер), записує бронь
--       і штовхає Telegram-бота.
--    4. Скасування — з бота кнопкою або з адмінки: статус
--       стає 'cancelled', і дата відразу звільняється в календарі.
-- ============================================================

-- ---------- 1) Броні ----------
create table if not exists public.bookings (
  id          bigint generated by default as identity primary key,
  site_id     bigint not null references public.sites (id) on delete cascade,
  ref         text not null default '',          -- номер для гостя: F-0110-234
  room_key    text not null default '',          -- technical key: standart, lyuks…
  room_name   text not null default '',          -- як номер звався на момент броні
  rooms_count int  not null default 1,           -- скільки номерів цього типу взяли
  date_in     date not null,
  date_out    date not null,
  adults      int  not null default 1,
  children    int  not null default 0,
  guest       jsonb not null default '{}',       -- {name, phone, via, note}
  extras      jsonb not null default '{}',       -- {sauna:{day,time,hours}}
  total       numeric not null default 0,
  status      text not null default 'new'
              check (status in ('new', 'confirmed', 'cancelled')),
  note        text not null default '',          -- примітка власника
  tg_sent_at  timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists bookings_site_at   on public.bookings (site_id, created_at desc);
create index if not exists bookings_site_room on public.bookings (site_id, room_key, date_in);

-- Телефонні броні власник заводить в адмінці руками — щоб дата
-- так само зайнялась у календарі на сайті. Звідки прийшла бронь:
alter table public.bookings add column if not exists source text not null default 'site'
  check (source in ('site', 'phone', 'other'));

-- ---------- 2) Хто що бачить ----------
alter table public.bookings enable row level security;

-- Броні бачить і править лише власник свого сайту (та власник платформи).
-- Гість не читає чужі броні — на сайт віддаються лише зайняті ДАТИ,
-- через окрему функцію нижче.
drop policy if exists "bookings owner read" on public.bookings;
create policy "bookings owner read" on public.bookings
  for select to authenticated using (public.is_admin() or site_id = public.my_site());

drop policy if exists "bookings owner write" on public.bookings;
create policy "bookings owner write" on public.bookings
  for update to authenticated using (public.is_admin() or site_id = public.my_site())
  with check (public.is_admin() or site_id = public.my_site());

drop policy if exists "bookings owner insert" on public.bookings;
create policy "bookings owner insert" on public.bookings
  for insert to authenticated
  with check (public.is_admin() or site_id = public.my_site());

drop policy if exists "bookings owner delete" on public.bookings;
create policy "bookings owner delete" on public.bookings
  for delete to authenticated using (public.is_admin() or site_id = public.my_site());

-- ---------- 3) Скільки таких номерів є ----------
create or replace function public.room_units(p_site bigint, p_room text)
returns int
language sql stable security definer set search_path = public as
$$
  select greatest(1, coalesce(nullif(extra->>'units', '')::int, 1))
  from public.items
  where site_id = p_site and collection = 'rooms' and extra->>'key' = p_room
  limit 1
$$;

-- ---------- 4) Зайняті дати для календаря ----------
--  Віддає дати, на які номер цього типу вже розібрали.
--  День виїзду не рахуємо: гість виїжджає зранку, і цю ніч
--  номер уже може взяти наступний.
create or replace function public.booking_busy(p_site bigint, p_room text)
returns table (d date)
language sql stable security definer set search_path = public as
$$
  with nights as (
    select g.d::date as d, b.rooms_count
    from public.bookings b
    cross join lateral generate_series(b.date_in, b.date_out - 1, interval '1 day') as g(d)
    where b.site_id = p_site
      and b.room_key = p_room
      and b.status <> 'cancelled'
      and b.date_out > current_date
  )
  select d from nights
  group by d
  having sum(rooms_count) >= coalesce(public.room_units(p_site, p_room), 1)
  order by d
$$;

-- ---------- 5) Зайнятий час сауни ----------
--  Сауна одна, тож дві компанії на ту саму годину не пустимо.
--  Віддаємо, що й коли вже замовлено: сайт гасить ці години.
create or replace function public.sauna_busy(p_site bigint)
returns table (day date, from_hour int, hours int)
language sql stable security definer set search_path = public as
$$
  select (b.extras->'sauna'->>'day')::date,
         split_part(b.extras->'sauna'->>'time', ':', 1)::int,
         greatest(1, coalesce(nullif(b.extras->'sauna'->>'hours', '')::int, 2))
  from public.bookings b
  where b.site_id = p_site
    and b.status <> 'cancelled'
    and b.extras ? 'sauna'
    and (b.extras->'sauna'->>'day') ~ '^\d{4}-\d{2}-\d{2}$'
    and (b.extras->'sauna'->>'day')::date >= current_date
$$;

-- ---------- 6) Штовхнути бота ----------
create extension if not exists pg_net;

create or replace function public.booking_ping(p_booking bigint) returns void
language plpgsql security definer set search_path = public as
$fn$
begin
  perform net.http_post(
    url     := 'https://ortiatyxntdikaldepbp.supabase.co/functions/v1/tg-bot',
    body    := jsonb_build_object('booking', p_booking),
    headers := '{"Content-Type": "application/json"}'::jsonb
  );
exception when others then
  -- Бот недоступний — бронь усе одно збережена, підстраховка нижче дошле.
  null;
end
$fn$;

-- ---------- 7) Оформити бронь ----------
--  Повертає {ok:true, id, ref} або {ok:false, why:'busy'|'dates'|'room'}.
--  Перевірку вільних місць робимо тут, а не на сайті: поки гість
--  заповнював форму, останній номер могли забрати.
create or replace function public.place_booking(
  p_site     bigint,
  p_room     text,
  p_in       date,
  p_out      date,
  p_adults   int,
  p_children int,
  p_rooms    int,
  p_guest    jsonb,
  p_extras   jsonb,
  p_total    numeric
) returns jsonb
language plpgsql security definer set search_path = public as
$fn$
declare
  v_units int;
  v_name  text;
  v_take  int := greatest(1, coalesce(p_rooms, 1));
  v_peak  int;
  v_ref   text;
  v_id    bigint;
begin
  if p_in is null or p_out is null or p_out <= p_in then
    return jsonb_build_object('ok', false, 'why', 'dates');
  end if;
  if p_in < current_date then
    return jsonb_build_object('ok', false, 'why', 'dates');
  end if;

  select title, greatest(1, coalesce(nullif(extra->>'units', '')::int, 1))
    into v_name, v_units
  from public.items
  where site_id = p_site and collection = 'rooms' and extra->>'key' = p_room
  limit 1;

  if v_name is null then
    -- Номера з таким кодом у базі немає: сайт свіжіший за базу.
    -- Бронь усе одно приймаємо — власник розбереться, але місця не рахуємо.
    v_name := p_room;
    v_units := 1;
  end if;

  -- найзавантаженіша ніч із обраних
  select coalesce(max(taken), 0) into v_peak
  from (
    select sum(b.rooms_count) as taken
    from public.bookings b
    cross join lateral generate_series(b.date_in, b.date_out - 1, interval '1 day') as g(d)
    where b.site_id = p_site
      and b.room_key = p_room
      and b.status <> 'cancelled'
      and g.d >= p_in and g.d < p_out
    group by g.d
  ) t;

  if v_peak + v_take > v_units then
    return jsonb_build_object('ok', false, 'why', 'busy');
  end if;

  v_ref := 'F-' || to_char(now() at time zone 'Europe/Kyiv', 'DDMM') || '-' ||
           lpad((floor(random() * 900) + 100)::text, 3, '0');

  insert into public.bookings
    (site_id, ref, room_key, room_name, rooms_count, date_in, date_out,
     adults, children, guest, extras, total, source)
  values
    (p_site, v_ref, p_room, v_name, v_take, p_in, p_out,
     greatest(1, coalesce(p_adults, 1)), greatest(0, coalesce(p_children, 0)),
     coalesce(p_guest, '{}'::jsonb), coalesce(p_extras, '{}'::jsonb),
     coalesce(p_total, 0), 'site')
  returning id into v_id;

  perform public.booking_ping(v_id);

  return jsonb_build_object('ok', true, 'id', v_id, 'ref', v_ref);
end
$fn$;

-- ---------- 8) Скасувати бронь ----------
--  Кличе бот (службовим ключем) і адмінка (від імені власника).
create or replace function public.cancel_booking(p_id bigint)
returns jsonb
language plpgsql security definer set search_path = public as
$fn$
declare v_row public.bookings;
begin
  update public.bookings
     set status = 'cancelled', updated_at = now()
   where id = p_id and status <> 'cancelled'
  returning * into v_row;

  if v_row.id is null then
    return jsonb_build_object('ok', false, 'why', 'not-found');
  end if;
  return jsonb_build_object('ok', true, 'ref', v_row.ref, 'room', v_row.room_name);
end
$fn$;

-- ---------- 9) Кому що можна кликати ----------
-- Сайт (анонім) має право лише питати зайняті дати й лишати бронь.
grant execute on function public.booking_busy(bigint, text) to anon, authenticated;
grant execute on function public.sauna_busy(bigint)          to anon, authenticated;
grant execute on function public.room_units(bigint, text)    to anon, authenticated;
grant execute on function public.place_booking(bigint, text, date, date, int, int, int, jsonb, jsonb, numeric)
  to anon, authenticated;
-- Скасування — лише власник з адмінки або бот службовим ключем.
revoke execute on function public.cancel_booking(bigint) from anon;
grant  execute on function public.cancel_booking(bigint) to authenticated;

-- ---------- 10) Підстраховка: дошле те, що не пішло ----------
create extension if not exists pg_cron with schema pg_catalog;

create or replace function public.booking_resend() returns void
language plpgsql security definer set search_path = public as
$fn$
declare r record;
begin
  for r in
    select id from public.bookings
    where tg_sent_at is null
      and status <> 'cancelled'
      and created_at > now() - interval '1 day'
    order by id
    limit 20
  loop
    perform public.booking_ping(r.id);
  end loop;
end
$fn$;

select cron.unschedule('booking-resend')
where exists (select 1 from cron.job where jobname = 'booking-resend');

select cron.schedule('booking-resend', '*/2 * * * *', $cron$ select public.booking_resend(); $cron$);

-- Старі броні вважаємо надісланими, щоб підстраховка не розсилала архів.
update public.bookings set tg_sent_at = created_at
where tg_sent_at is null and created_at < now() - interval '1 day';
