-- ============================================================
--  СКЛАД для магазину одягу (платформа адмінок)
--
--  Що додається:
--    • залишки окремо по товар × розмір × колір;
--    • резерв на час оформлення — двоє не куплять останню одиницю;
--    • списання при замовленні й повернення при скасуванні;
--    • історія рухів: надходження, продаж, повернення, списання, виправлення;
--    • замовлення з сайту в базі, щоб було що скасовувати й повертати.
--
--  Нічого наявного не чіпає: sites, items, texts лишаються як були,
--  жоден товар не змінюється. Виконати ОДИН раз у Supabase → SQL Editor.
--  Повторний запуск безпечний.
-- ============================================================

-- ---------- 1) Таблиці ----------

-- Залишок однієї позиції: конкретний товар у конкретному розмірі (і кольорі).
create table if not exists public.stock (
  id         bigint generated by default as identity primary key,
  site_id    bigint not null references public.sites (id) on delete cascade,
  item_id    bigint not null references public.items (id) on delete cascade,
  size       text not null default '',
  color      text not null default '',
  qty        int  not null default 0 check (qty >= 0),       -- фізично лежить на складі
  reserved   int  not null default 0 check (reserved >= 0),  -- відкладено під кошики
  low_at     int  not null default 2,                        -- від скількох писати «закінчується»
  updated_at timestamptz not null default now(),
  unique (item_id, size, color)
);
create index if not exists stock_site_item on public.stock (site_id, item_id);

-- Історія: кожна зміна залишку окремим рядком, нічого не затирається.
create table if not exists public.stock_moves (
  id        bigint generated by default as identity primary key,
  site_id   bigint not null references public.sites (id) on delete cascade,
  item_id   bigint not null references public.items (id) on delete cascade,
  size      text not null default '',
  color     text not null default '',
  kind      text not null check (kind in ('in', 'sale', 'return', 'writeoff', 'fix')),
  delta     int  not null,          -- на скільки змінився залишок (+ прихід, − розхід)
  qty_after int  not null,          -- скільки стало після цієї зміни
  note      text not null default '',
  order_ref text not null default '',
  who       text not null default '',
  at        timestamptz not null default now()
);
create index if not exists stock_moves_site_at on public.stock_moves (site_id, at desc);
create index if not exists stock_moves_item on public.stock_moves (item_id, at desc);

-- Замовлення з сайту. Потрібні, щоб було звідки списувати й куди повертати.
create table if not exists public.orders (
  id         bigint generated by default as identity primary key,
  site_id    bigint not null references public.sites (id) on delete cascade,
  ref        text not null default '',              -- номер для покупця: 2609-0007
  status     text not null default 'new' check (status in ('new', 'done', 'cancelled', 'returned')),
  customer   jsonb not null default '{}',           -- імʼя, телефон, доставка
  lines      jsonb not null default '[]',           -- [{item_id, size, color, qty, title, price}]
  total      numeric not null default 0,
  note       text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists orders_site_at on public.orders (site_id, created_at desc);

-- Відкладене під кошик, який ще оформлюють. Живе 15 хвилин.
create table if not exists public.stock_holds (
  token   uuid primary key,
  site_id bigint not null references public.sites (id) on delete cascade,
  lines   jsonb not null default '[]',
  until   timestamptz not null
);
create index if not exists stock_holds_until on public.stock_holds (until);

-- ---------- 2) Хто що може ----------

alter table public.stock       enable row level security;
alter table public.stock_moves enable row level security;
alter table public.orders      enable row level security;
alter table public.stock_holds enable row level security;

-- Залишки читають усі: сайт має знати, чи є розмір у наявності.
-- Пишуть — лише через функції нижче, щоб кожна зміна лягала в історію.
drop policy if exists "stock public read" on public.stock;
create policy "stock public read" on public.stock for select using (true);

-- Історію й замовлення бачить лише власник свого сайту (і власник платформи).
drop policy if exists "moves owner read" on public.stock_moves;
create policy "moves owner read" on public.stock_moves
  for select to authenticated using (public.is_admin() or site_id = public.my_site());

drop policy if exists "orders owner read" on public.orders;
create policy "orders owner read" on public.orders
  for select to authenticated using (public.is_admin() or site_id = public.my_site());

drop policy if exists "orders owner update" on public.orders;
create policy "orders owner update" on public.orders
  for update to authenticated
  using (public.is_admin() or site_id = public.my_site())
  with check (public.is_admin() or site_id = public.my_site());

-- stock_holds не читає ніхто ззовні: це службова таблиця функцій.

-- ---------- 3) Помічники ----------

-- Чи має нинішній користувач право правити склад цього сайту
create or replace function public.stock_can_edit(p_site bigint) returns boolean
language sql stable security definer set search_path = public as
$fn$ select public.is_admin() or (p_site = public.my_site() and public.site_paid(p_site)) $fn$;

-- Підпис у історії: пошта власника або «сайт»
create or replace function public.stock_who() returns text
language sql stable security definer set search_path = public as
$fn$ select coalesce((select email from auth.users where id = auth.uid()), 'сайт') $fn$;

-- Зняти відкладене за одним кошиком
create or replace function public.stock_drop_hold(p_token uuid) returns void
language plpgsql security definer set search_path = public as
$fn$
declare h record; l jsonb;
begin
  select * into h from stock_holds where token = p_token;
  if not found then return; end if;
  for l in select value from jsonb_array_elements(h.lines) loop
    update stock set reserved = greatest(0, reserved - greatest(coalesce((l->>'qty')::int, 1), 1)),
                     updated_at = now()
     where item_id = (l->>'item_id')::bigint
       and size = coalesce(l->>'size', '')
       and color = coalesce(l->>'color', '');
  end loop;
  delete from stock_holds where token = p_token;
end
$fn$;

-- Повернути в продаж усе, що відклали й не оформили
create or replace function public.stock_release_expired() returns void
language plpgsql security definer set search_path = public as
$fn$
declare t uuid;
begin
  for t in select token from stock_holds where until < now() loop
    perform public.stock_drop_hold(t);
  end loop;
end
$fn$;

-- ---------- 4) Склад: ручні дії власника ----------

-- Надходження (+), списання (−) або виправлення до точного числа.
-- Рядок складу створюється сам, якщо його ще не було.
create or replace function public.stock_adjust(
  p_item bigint, p_size text, p_color text, p_delta int, p_kind text, p_note text
) returns jsonb
language plpgsql security definer set search_path = public as
$fn$
declare v_site bigint; s record; v_after int;
begin
  if p_kind not in ('in', 'writeoff', 'fix') then
    return jsonb_build_object('ok', false, 'error', 'kind');
  end if;
  select site_id into v_site from items where id = p_item;
  if v_site is null then return jsonb_build_object('ok', false, 'error', 'item'); end if;
  if not public.stock_can_edit(v_site) then
    return jsonb_build_object('ok', false, 'error', 'access');
  end if;

  select * into s from stock
   where item_id = p_item and size = coalesce(p_size, '') and color = coalesce(p_color, '')
   for update;
  if not found then
    insert into stock (site_id, item_id, size, color, qty)
    values (v_site, p_item, coalesce(p_size, ''), coalesce(p_color, ''), 0)
    returning * into s;
  end if;

  v_after := s.qty + p_delta;
  if v_after < 0 then
    return jsonb_build_object('ok', false, 'error', 'negative', 'left', s.qty);
  end if;

  update stock set qty = v_after, updated_at = now() where id = s.id;
  insert into stock_moves (site_id, item_id, size, color, kind, delta, qty_after, note, who)
  values (v_site, p_item, s.size, s.color, p_kind, p_delta, v_after,
          coalesce(p_note, ''), public.stock_who());

  return jsonb_build_object('ok', true, 'qty', v_after);
end
$fn$;

-- Поріг «закінчується» для однієї позиції
create or replace function public.stock_set_low(p_item bigint, p_size text, p_color text, p_low int)
returns jsonb language plpgsql security definer set search_path = public as
$fn$
declare v_site bigint;
begin
  select site_id into v_site from items where id = p_item;
  if v_site is null or not public.stock_can_edit(v_site) then
    return jsonb_build_object('ok', false, 'error', 'access');
  end if;
  update stock set low_at = greatest(0, coalesce(p_low, 2)), updated_at = now()
   where item_id = p_item and size = coalesce(p_size, '') and color = coalesce(p_color, '');
  return jsonb_build_object('ok', true);
end
$fn$;

-- Завести рядки складу для розмірів, яких ще нема (нові товари підхоплюються самі).
create or replace function public.stock_sync(p_site bigint) returns int
language plpgsql security definer set search_path = public as
$fn$
declare col text; fld text; it record; sz text; n int := 0;
begin
  if not public.stock_can_edit(p_site) then return 0; end if;
  select coalesce(config->>'stockCollection', 'products'),
         coalesce(config->>'stockSizes', 'sizes')
    into col, fld from sites where id = p_site;

  for it in select id, extra from items where site_id = p_site and collection = col loop
    for sz in select btrim(x) from unnest(string_to_array(coalesce(it.extra->>fld, ''), ',')) as x loop
      if sz <> '' then
        insert into stock (site_id, item_id, size, color, qty)
        values (p_site, it.id, sz, '', 0)
        on conflict (item_id, size, color) do nothing;
        if found then n := n + 1; end if;
      end if;
    end loop;
  end loop;
  return n;
end
$fn$;

-- ---------- 5) Сайт: резерв і замовлення ----------

-- Відкласти кошик на 15 хвилин. Повертає, чого не вистачає.
create or replace function public.stock_hold(p_site bigint, p_token uuid, p_lines jsonb)
returns jsonb language plpgsql security definer set search_path = public as
$fn$
declare l jsonb; s record; need int; short jsonb := '[]'::jsonb; v_until timestamptz;
begin
  if not exists (select 1 from sites where id = p_site and paid_until >= current_date) then
    return jsonb_build_object('ok', false, 'error', 'site');
  end if;
  if jsonb_typeof(p_lines) <> 'array' or jsonb_array_length(p_lines) > 50 then
    return jsonb_build_object('ok', false, 'error', 'lines');
  end if;

  perform public.stock_release_expired();
  perform public.stock_drop_hold(p_token);

  -- спершу перевіряємо все, і лише потім відкладаємо: часткового резерву не буває
  for l in select value from jsonb_array_elements(p_lines) loop
    need := least(greatest(coalesce((l->>'qty')::int, 1), 1), 20);
    select * into s from stock
     where site_id = p_site and item_id = (l->>'item_id')::bigint
       and size = coalesce(l->>'size', '') and color = coalesce(l->>'color', '')
     for update;
    if found and s.qty - s.reserved < need then
      short := short || jsonb_build_array(jsonb_build_object(
        'item_id', s.item_id, 'size', s.size, 'left', greatest(s.qty - s.reserved, 0)));
    end if;
  end loop;

  if jsonb_array_length(short) > 0 then
    return jsonb_build_object('ok', false, 'short', short);
  end if;

  for l in select value from jsonb_array_elements(p_lines) loop
    need := least(greatest(coalesce((l->>'qty')::int, 1), 1), 20);
    update stock set reserved = reserved + need, updated_at = now()
     where site_id = p_site and item_id = (l->>'item_id')::bigint
       and size = coalesce(l->>'size', '') and color = coalesce(l->>'color', '');
  end loop;

  v_until := now() + interval '15 minutes';
  insert into stock_holds (token, site_id, lines, until) values (p_token, p_site, p_lines, v_until);
  return jsonb_build_object('ok', true, 'until', v_until);
end
$fn$;

-- Покупець пішов з оформлення — повертаємо відкладене в продаж
create or replace function public.stock_unhold(p_token uuid) returns jsonb
language plpgsql security definer set search_path = public as
$fn$
begin
  perform public.stock_drop_hold(p_token);
  return jsonb_build_object('ok', true);
end
$fn$;

-- Оформлення: перевірка, списання, історія й саме замовлення — одним заходом.
create or replace function public.place_order(
  p_site bigint, p_token uuid, p_lines jsonb, p_customer jsonb, p_total numeric
) returns jsonb
language plpgsql security definer set search_path = public as
$fn$
declare l jsonb; s record; need int; short jsonb := '[]'::jsonb;
        v_id bigint; v_ref text; v_after int;
begin
  if not exists (select 1 from sites where id = p_site and paid_until >= current_date) then
    return jsonb_build_object('ok', false, 'error', 'site');
  end if;
  if jsonb_typeof(p_lines) <> 'array'
     or jsonb_array_length(p_lines) = 0 or jsonb_array_length(p_lines) > 50
     or length(coalesce(p_customer::text, '')) > 4000 then
    return jsonb_build_object('ok', false, 'error', 'lines');
  end if;

  perform public.stock_release_expired();
  perform public.stock_drop_hold(p_token);   -- своє відкладене зараз стане продажем

  for l in select value from jsonb_array_elements(p_lines) loop
    need := least(greatest(coalesce((l->>'qty')::int, 1), 1), 20);
    select * into s from stock
     where site_id = p_site and item_id = (l->>'item_id')::bigint
       and size = coalesce(l->>'size', '') and color = coalesce(l->>'color', '')
     for update;
    if found and s.qty - s.reserved < need then
      short := short || jsonb_build_array(jsonb_build_object(
        'item_id', s.item_id, 'size', s.size,
        'title', coalesce(l->>'title', ''), 'left', greatest(s.qty - s.reserved, 0)));
    end if;
  end loop;

  if jsonb_array_length(short) > 0 then
    return jsonb_build_object('ok', false, 'short', short);
  end if;

  insert into orders (site_id, ref, status, customer, lines, total)
  values (p_site, '', 'new', coalesce(p_customer, '{}'::jsonb), p_lines, coalesce(p_total, 0))
  returning id into v_id;
  v_ref := to_char(now(), 'DDMM') || '-' || lpad(v_id::text, 4, '0');
  update orders set ref = v_ref where id = v_id;

  for l in select value from jsonb_array_elements(p_lines) loop
    need := least(greatest(coalesce((l->>'qty')::int, 1), 1), 20);
    update stock set qty = qty - need, updated_at = now()
     where site_id = p_site and item_id = (l->>'item_id')::bigint
       and size = coalesce(l->>'size', '') and color = coalesce(l->>'color', '')
    returning qty into v_after;
    if found then
      insert into stock_moves (site_id, item_id, size, color, kind, delta, qty_after, note, order_ref, who)
      values (p_site, (l->>'item_id')::bigint, coalesce(l->>'size', ''), coalesce(l->>'color', ''),
              'sale', -need, v_after, 'замовлення з сайту', v_ref, 'сайт');
    end if;
  end loop;

  return jsonb_build_object('ok', true, 'ref', v_ref, 'id', v_id);
end
$fn$;

-- Зміна статусу замовлення власником: скасування й повернення самі кладуть товар назад.
create or replace function public.set_order_status(p_order bigint, p_status text)
returns jsonb language plpgsql security definer set search_path = public as
$fn$
declare o record; l jsonb; need int; v_after int; back boolean; take boolean;
begin
  if p_status not in ('new', 'done', 'cancelled', 'returned') then
    return jsonb_build_object('ok', false, 'error', 'status');
  end if;
  select * into o from orders where id = p_order for update;
  if not found then return jsonb_build_object('ok', false, 'error', 'order'); end if;
  if not public.stock_can_edit(o.site_id) then
    return jsonb_build_object('ok', false, 'error', 'access');
  end if;
  if o.status = p_status then return jsonb_build_object('ok', true); end if;

  -- товар лічиться відданим, поки замовлення «нове» або «виконане»
  back := o.status in ('new', 'done') and p_status in ('cancelled', 'returned');
  take := o.status in ('cancelled', 'returned') and p_status in ('new', 'done');

  if back or take then
    for l in select value from jsonb_array_elements(o.lines) loop
      need := least(greatest(coalesce((l->>'qty')::int, 1), 1), 20);
      update stock set qty = case when back then qty + need else greatest(0, qty - need) end,
                       updated_at = now()
       where site_id = o.site_id and item_id = (l->>'item_id')::bigint
         and size = coalesce(l->>'size', '') and color = coalesce(l->>'color', '')
      returning qty into v_after;
      if found then
        insert into stock_moves (site_id, item_id, size, color, kind, delta, qty_after, note, order_ref, who)
        values (o.site_id, (l->>'item_id')::bigint, coalesce(l->>'size', ''), coalesce(l->>'color', ''),
                case when back then 'return' else 'sale' end,
                case when back then need else -need end, v_after,
                case when p_status = 'cancelled' then 'скасування замовлення'
                     when p_status = 'returned'  then 'повернення від покупця'
                     else 'замовлення поновлено' end,
                o.ref, public.stock_who());
      end if;
    end loop;
  end if;

  update orders set status = p_status, updated_at = now() where id = p_order;
  return jsonb_build_object('ok', true);
end
$fn$;

-- ---------- 6) Кому дозволено викликати ----------

revoke all on function public.stock_adjust(bigint, text, text, int, text, text) from public;
revoke all on function public.stock_set_low(bigint, text, text, int) from public;
revoke all on function public.stock_sync(bigint) from public;
revoke all on function public.set_order_status(bigint, text) from public;
revoke all on function public.stock_hold(bigint, uuid, jsonb) from public;
revoke all on function public.stock_unhold(uuid) from public;
revoke all on function public.place_order(bigint, uuid, jsonb, jsonb, numeric) from public;
revoke all on function public.stock_drop_hold(uuid) from public;
revoke all on function public.stock_release_expired() from public;

grant execute on function public.stock_adjust(bigint, text, text, int, text, text) to authenticated;
grant execute on function public.stock_set_low(bigint, text, text, int) to authenticated;
grant execute on function public.stock_sync(bigint) to authenticated;
grant execute on function public.set_order_status(bigint, text) to authenticated;
grant execute on function public.stock_hold(bigint, uuid, jsonb) to anon, authenticated;
grant execute on function public.stock_unhold(uuid) to anon, authenticated;
grant execute on function public.place_order(bigint, uuid, jsonb, jsonb, numeric) to anon, authenticated;

-- ---------- 7) Увімкнути склад у Just shop ----------
--  Додаємо лише прапорець у конфіг — решта конфіга й товари не змінюються.

update public.sites
   set config = config || jsonb_build_object('stock', true,
                                             'stockCollection', 'products',
                                             'stockSizes', 'sizes')
 where slug = 'justshop';

select count(*) as "позицій складу" from public.stock
 where site_id = (select id from public.sites where slug = 'justshop');
