-- ============================================================
--  ЖУРНАЛ ЗАЯВОК — спільний для всіх сайтів платформи
--  Заявки з форм бронювання та замовлення меню падають сюди
--  і показуються в адмінці. Гість пише анонімно, читає лише
--  власник сайту (або власник платформи).
--  Запускати ОДИН раз у SQL Editor. Безпечно перезапускати.
-- ============================================================

create table if not exists public.leads (
  id          bigint generated by default as identity primary key,
  site_id     bigint not null references public.sites (id) on delete cascade,
  kind        text   not null default 'booking',   -- booking | order
  number      text,                                 -- напр. Ф-3007-014-K9
  name        text,
  phone       text,
  summary     text,                                 -- готовий текст заявки
  total       numeric,                              -- сума замовлення, якщо є
  payload     jsonb  not null default '{}',         -- усі поля як прийшли
  status      text   not null default 'new'
              check (status in ('new', 'done', 'cancelled')),
  created_at  timestamptz not null default now()
);

create index if not exists leads_site_created on public.leads (site_id, created_at desc);
create index if not exists leads_site_status  on public.leads (site_id, status);

alter table public.leads enable row level security;

-- Гість надсилає заявку анонімно. Навмисно БЕЗ перевірки підписки:
-- прострочена оплата не повинна коштувати клієнту втрачених замовлень.
drop policy if exists "leads insert public" on public.leads;
create policy "leads insert public" on public.leads
  for insert with check (true);

-- Читає лише власник свого сайту або власник платформи.
drop policy if exists "leads read own" on public.leads;
create policy "leads read own" on public.leads
  for select using (public.is_admin() or site_id = public.my_site());

-- Змінювати статус — так само.
drop policy if exists "leads update own" on public.leads;
create policy "leads update own" on public.leads
  for update using (public.is_admin() or site_id = public.my_site())
  with check (public.is_admin() or site_id = public.my_site());

drop policy if exists "leads delete own" on public.leads;
create policy "leads delete own" on public.leads
  for delete using (public.is_admin() or site_id = public.my_site());
