-- ============================================================
--  МІГРАЦІЯ (v2): SUSHI SHARK — меню 3 мовами + вимикач «Вихідний»
--  Виправлено: коди фото, обʼєм напоїв, промо, можливість міняти фото
--  Безпечно перезапускати: спершу чистить дані сайту 3
--  Запускати у SQL Editor проєкту platform
-- ============================================================

-- 1) Сайт (створити або оновити конфіг)
insert into public.sites (id, slug, name, paid_until, config) values (
  3, 'sushishark', 'SUSHI SHARK', current_date + 30,
  '{"collections":[{"key":"menu","name":"Меню","fields":[{"key":"title","name":"Назва (як у меню)","type":"text"},{"key":"price","name":"Ціна, zł","type":"text"},{"key":"image","name":"Фото страви","type":"image"},{"key":"cat","name":"Категорія","type":"select-collection","from":"cats","extra":true},{"key":"pcs","name":"Кількість шматочків","type":"text","extra":true},{"key":"vol","name":"Обʼєм / підпис замість «шт» (напої, сети)","type":"text","extra":true},{"key":"spicy","name":"Гострота: порожньо, 1, 2 або 3","type":"text","extra":true},{"key":"veg","name":"Вегетаріанська","type":"checkbox","extra":true},{"key":"promo","name":"Промо (показувати першою)","type":"checkbox","extra":true},{"key":"pl","name":"Склад польською","type":"textarea","extra":true},{"key":"ua","name":"Склад українською","type":"textarea","extra":true},{"key":"en","name":"Склад англійською","type":"textarea","extra":true},{"key":"img","name":"Код вбудованого фото (не міняти!)","type":"text","extra":true}]},{"key":"cats","name":"Категорії (нових не додавати)","fields":[{"key":"title","name":"Назва","type":"text"},{"key":"catkey","name":"Код (не міняти!)","type":"text","extra":true}]},{"key":"settings","name":"Режим роботи","fields":[{"key":"title","name":"Назва картки (не міняти)","type":"text"},{"key":"dayoff","name":"СЬОГОДНІ ВИХІДНИЙ (закрити сайт)","type":"checkbox","extra":true},{"key":"msg_pl","name":"Текст банера польською","type":"text","extra":true},{"key":"msg_ua","name":"Текст банера українською","type":"text","extra":true}]}],"texts":[]}'
)
on conflict (id) do update set config = excluded.config, name = excluded.name;

select setval(pg_get_serial_sequence('public.sites', 'id'), (select max(id) from public.sites));

-- 2) Чистимо старий вміст цього сайту
delete from public.items where site_id = 3;

-- 3) Категорії
insert into public.items (site_id, collection, title, extra, sort_order) values
  (3, 'cats', 'Роли', '{"catkey":"rolls"}', 1),
  (3, 'cats', 'Каліфорнія', '{"catkey":"california"}', 2),
  (3, 'cats', 'Теплі роли', '{"catkey":"warm"}', 3),
  (3, 'cats', 'Макі та нігірі', '{"catkey":"maki"}', 4),
  (3, 'cats', 'Суші-бургери', '{"catkey":"burgers"}', 5),
  (3, 'cats', 'Сети', '{"catkey":"sets"}', 6),
  (3, 'cats', 'Напої', '{"catkey":"drinks"}', 7),
  (3, 'cats', 'Соуси та добавки', '{"catkey":"sosy"}', 8);

-- 4) Вимикач «Вихідний»
insert into public.items (site_id, collection, title, extra, sort_order) values
  (3, 'settings', 'Вимикач «Вихідний»', '{"msg_pl":"Dziś mamy wolne 🦈 Zapraszamy jutro!","msg_ua":"Сьогодні вихідний 🦈 Чекаємо вас завтра!"}', 1);

-- 5) Меню (97 позицій)
insert into public.items (site_id, collection, title, price, extra, sort_order) values
  (3, 'menu', 'Łosoś & serek', '45', '{"cat":"rolls","img":"p1","pcs":"8","pl":"łosoś, ser, mango, kanpyo, cheddar, sweet chili mayo, migdał","ua":"лосось, сир, манго, канпьо, чеддер, sweet chili mayo, мигдаль","en":"salmon, cream cheese, mango, kanpyo, cheddar, sweet chili mayo, almond"}', 1),
  (3, 'menu', 'Ayame', '44', '{"cat":"rolls","img":"p2","pcs":"8","pl":"krewetki, ser, mango, kanpyo, łosoś","ua":"креветки, сир, манго, канпьо, лосось","en":"prawns, cream cheese, mango, kanpyo, salmon"}', 2),
  (3, 'menu', 'Yami', '49', '{"cat":"rolls","img":"p3","pcs":"8","pl":"sezam, krewetki, ser, ogórek, łosoś, awokado, sos orzechowy","ua":"кунжут, креветки, сир, огірок, лосось, авокадо, горіховий соус","en":"sesame, prawns, cream cheese, cucumber, salmon, avocado, peanut sauce"}', 3),
  (3, 'menu', 'Pikantny', '57', '{"cat":"rolls","img":"p4","pcs":"8","pl":"węgorz unagi, ser, ogórek, łosoś smażony, sweet chili mayo, sriracha, sezam","ua":"вугор унагі, сир, огірок, смажений лосось, sweet chili mayo, шрірача, кунжут","en":"unagi eel, cream cheese, cucumber, fried salmon, sweet chili mayo, sriracha, sesame","spicy":"2"}', 4),
  (3, 'menu', 'Spicy łosoś', '50', '{"cat":"rolls","img":"p5","pcs":"8","pl":"ser, ogórek, łosoś, sweet chili mayo, sriracha, kawior","ua":"сир, огірок, лосось, sweet chili mayo, шрірача, ікра","en":"cream cheese, cucumber, salmon, sweet chili mayo, sriracha, caviar","spicy":"2"}', 5),
  (3, 'menu', 'Gejsza', '39', '{"cat":"rolls","img":"p6","pcs":"8","pl":"łosoś, ser, kanpyo, awokado, ogórek, sos unagi, sezam","ua":"лосось, сир, канпьо, авокадо, огірок, соус унагі, кунжут","en":"salmon, cream cheese, kanpyo, avocado, cucumber, unagi sauce, sesame"}', 6),
  (3, 'menu', 'Rolka z krewetkami pańko', '46', '{"cat":"rolls","img":"p7","pcs":"8","pl":"krewetki panko, ogórek, daikon, ser, tobiko","ua":"креветки панко, огірок, дайкон, сир, тобіко","en":"panko prawns, cucumber, daikon, cream cheese, tobiko"}', 7),
  (3, 'menu', 'California Yaki', '40', '{"cat":"california","img":"p8","pcs":"8","pl":"łosoś smażony, ogórek, tuńczyk suszony, ser, sos unagi","ua":"смажений лосось, огірок, сушений тунець, сир, соус унагі","en":"fried salmon, cucumber, dried tuna flakes, cream cheese, unagi sauce"}', 8),
  (3, 'menu', 'Rolka na ciepło z łososiem', '43', '{"cat":"warm","img":"p9","pcs":"8","pl":"łosoś, ogórek, ser topiony, gouda, słodki chili, sos unagi","ua":"лосось, огірок, плавлений сир, гауда, солодкий чилі, соус унагі","en":"salmon, cucumber, melted cheese, gouda, sweet chili, unagi sauce"}', 9),
  (3, 'menu', 'Rolka na ciepło z krewetkami', '43', '{"cat":"warm","img":"p10","pcs":"8","pl":"krewetki, ogórek, ser topiony, gouda, słodki chili, sos unagi","ua":"креветки, огірок, плавлений сир, гауда, солодкий чилі, соус унагі","en":"prawns, cucumber, melted cheese, gouda, sweet chili, unagi sauce"}', 10),
  (3, 'menu', 'Rolka na ciepło z węgorzem', '45', '{"cat":"warm","img":"p11","pcs":"8","pl":"węgorz, ogórek, daikon, ser topiony, gouda, słodki chili, sos unagi","ua":"вугор, огірок, дайкон, плавлений сир, гауда, солодкий чилі, соус унагі","en":"eel, cucumber, daikon, melted cheese, gouda, sweet chili, unagi sauce"}', 11),
  (3, 'menu', 'Rolka na ciepło mix', '45', '{"cat":"warm","img":"p12","pcs":"8","pl":"surimi, ogórek, ser topiony, gouda, łosoś, krewetki","ua":"сурімі, огірок, плавлений сир, гауда, лосось, креветки","en":"surimi, cucumber, melted cheese, gouda, salmon, prawns"}', 12),
  (3, 'menu', 'California unagi', '43', '{"cat":"california","img":"p13","pcs":"8","pl":"węgorz, ser, ogórek, sezam, sos unagi","ua":"вугор, сир, огірок, кунжут, соус унагі","en":"eel, cream cheese, cucumber, sesame, unagi sauce"}', 13),
  (3, 'menu', 'California tuna', '35', '{"cat":"california","img":"p14","pcs":"8","pl":"tuńczyk, ser, ogórek, sezam","ua":"тунець, сир, огірок, кунжут","en":"tuna, cream cheese, cucumber, sesame"}', 14),
  (3, 'menu', 'California crunch', '40', '{"cat":"california","img":"p15","pcs":"8","pl":"łosoś, ser, ogórek, sweet chili mayo, sos unagi, cebula prażona","ua":"лосось, сир, огірок, sweet chili mayo, соус унагі, смажена цибулька","en":"salmon, cream cheese, cucumber, sweet chili mayo, unagi sauce, crispy onion"}', 15),
  (3, 'menu', 'California Mango łosoś', '37', '{"cat":"california","img":"p16","pcs":"8","pl":"łosoś, mango, gruszka, kanpyo, sezam, ser, sweet chili mayo","ua":"лосось, манго, груша, канпьо, кунжут, сир, sweet chili mayo","en":"salmon, mango, pear, kanpyo, sesame, cream cheese, sweet chili mayo"}', 16),
  (3, 'menu', 'California de Lux', '51', '{"cat":"california","img":"p17","pcs":"8","pl":"łosoś, daikon, ogórek, masago, ser, krewetki","ua":"лосось, дайкон, огірок, масаго, сир, креветки","en":"salmon, daikon, cucumber, masago, cream cheese, prawns"}', 17),
  (3, 'menu', 'California krab', '30', '{"cat":"california","img":"p18","pcs":"8","pl":"surimi, ogórek, ser, masago","ua":"сурімі, огірок, сир, масаго","en":"surimi, cucumber, cream cheese, masago"}', 18),
  (3, 'menu', 'California ebi', '38', '{"cat":"california","img":"p19","pcs":"8","pl":"krewetki, ser, ogórek, masago","ua":"креветки, сир, огірок, масаго","en":"prawns, cream cheese, cucumber, masago"}', 19),
  (3, 'menu', 'California sake', '37', '{"cat":"california","img":"p20","pcs":"8","pl":"łosoś, ser, ogórek, masago","ua":"лосось, сир, огірок, масаго","en":"salmon, cream cheese, cucumber, masago"}', 20),
  (3, 'menu', 'Mega tempura', '50', '{"cat":"warm","img":"p21","pcs":"8","pl":"łosoś, krewetka, tuńczyk, ser, kanpyo, ogórek, panierka, sweet chili mayo, sos orzechowy","ua":"лосось, креветка, тунець, сир, канпьо, огірок, паніровка, sweet chili mayo, горіховий соус","en":"salmon, prawn, tuna, cream cheese, kanpyo, cucumber, breading, sweet chili mayo, peanut sauce"}', 21),
  (3, 'menu', 'Tempura sake', '43', '{"cat":"warm","img":"p22","pcs":"8","pl":"łosoś, ser, ogórek, panierka panko, sweet chili mayo, sos orzechowy","ua":"лосось, сир, огірок, паніровка панко, sweet chili mayo, горіховий соус","en":"salmon, cream cheese, cucumber, panko breading, sweet chili mayo, peanut sauce"}', 22),
  (3, 'menu', 'Tempura ebi', '42', '{"cat":"warm","img":"p23","pcs":"8","pl":"krewetki, ser, ogórek, panierka panko, sos unagi, sos orzechowy","ua":"креветки, сир, огірок, паніровка панко, соус унагі, горіховий соус","en":"prawns, cream cheese, cucumber, panko breading, unagi sauce, peanut sauce"}', 23),
  (3, 'menu', 'Tuna tempura', '45', '{"cat":"warm","img":"p24","pcs":"8","pl":"tuńczyk, ser, ogórek, panierka tempura, sweet chili mayo, sos orzechowy","ua":"тунець, сир, огірок, паніровка темпура, sweet chili mayo, горіховий соус","en":"tuna, cream cheese, cucumber, tempura batter, sweet chili mayo, peanut sauce"}', 24),
  (3, 'menu', 'Sake maki', '20', '{"cat":"maki","img":"p25","pcs":"8","pl":"łosoś","ua":"лосось","en":"salmon"}', 25),
  (3, 'menu', 'Maki ebi', '25', '{"cat":"maki","img":"p26","pcs":"8","pl":"krewetki","ua":"креветки","en":"prawns"}', 26),
  (3, 'menu', 'Unagi maki', '25', '{"cat":"maki","img":"p27","pcs":"8","pl":"węgorz, sezam, sos unagi","ua":"вугор, кунжут, соус унагі","en":"eel, sesame, unagi sauce"}', 27),
  (3, 'menu', 'Maki kanpyo', '15', '{"cat":"maki","img":"p28","pcs":"8","pl":"kanpyo","ua":"канпьо","en":"kanpyo"}', 28),
  (3, 'menu', 'Tuna maki', '20', '{"cat":"maki","img":"p29","pcs":"8","pl":"tuńczyk","ua":"тунець","en":"tuna"}', 29),
  (3, 'menu', 'Maki z ogórkiem', '15', '{"cat":"maki","img":"p30","pcs":"8","pl":"ogórek","ua":"огірок","en":"cucumber","veg":true}', 30),
  (3, 'menu', 'Krab maki', '16', '{"cat":"maki","img":"p31","pcs":"8","pl":"surimi","ua":"сурімі","en":"surimi"}', 31),
  (3, 'menu', 'Awokado maki', '16', '{"cat":"maki","img":"p32","pcs":"8","pl":"awokado, sos unagi, sezam","ua":"авокадо, соус унагі, кунжут","en":"avocado, unagi sauce, sesame","veg":true}', 32),
  (3, 'menu', 'California łosoś rukola', '42', '{"cat":"california","img":"p33","pcs":"8","pl":"łosoś, rukola, ogórek, ser, sezam, sos mango","ua":"лосось, рукола, огірок, сир, кунжут, соус манго","en":"salmon, arugula, cucumber, cream cheese, sesame, mango sauce"}', 33),
  (3, 'menu', 'Tempura unagi', '47', '{"cat":"warm","img":"p34","pcs":"8","pl":"węgorz, ser, ogórek, panierka, sos unagi, sos orzechowy","ua":"вугор, сир, огірок, паніровка, соус унагі, горіховий соус","en":"eel, cream cheese, cucumber, breading, unagi sauce, peanut sauce"}', 34),
  (3, 'menu', 'Tempura mix', '42', '{"cat":"warm","img":"p35","pcs":"8","pl":"łosoś, surimi, ogórek, panierka tempura, sweet chili mayo, sos orzechowy","ua":"лосось, сурімі, огірок, паніровка темпура, sweet chili mayo, горіховий соус","en":"salmon, surimi, cucumber, tempura batter, sweet chili mayo, peanut sauce"}', 35),
  (3, 'menu', 'Futomaki z łososiem panko', '32', '{"cat":"rolls","img":"p36","pcs":"8","pl":"łosoś smażony w panko, ogórek, gruszka, sweet chili mayo, cebula prażona","ua":"лосось у панко, огірок, груша, sweet chili mayo, смажена цибулька","en":"panko-fried salmon, cucumber, pear, sweet chili mayo, crispy onion"}', 36),
  (3, 'menu', 'Nigiri z łososiem', '15', '{"cat":"maki","img":"p37","pcs":"2","pl":"łosoś na ryżu sushi","ua":"лосось на рисі суші","en":"salmon on sushi rice"}', 37),
  (3, 'menu', 'Nigiri z tuńczykiem', '15', '{"cat":"maki","img":"p38","pcs":"2","pl":"tuńczyk na ryżu sushi","ua":"тунець на рисі суші","en":"tuna on sushi rice"}', 38),
  (3, 'menu', 'Nigiri z krewetkami', '15', '{"cat":"maki","img":"p39","pcs":"2","pl":"krewetka na ryżu sushi","ua":"креветка на рисі суші","en":"prawn on sushi rice"}', 39),
  (3, 'menu', 'Nigiri z węgorzem', '18', '{"cat":"maki","img":"p40","pcs":"2","pl":"węgorz na ryżu sushi","ua":"вугор на рисі суші","en":"eel on sushi rice"}', 40),
  (3, 'menu', 'Żółty smok z węgorzem', '41', '{"cat":"rolls","img":"p41","pcs":"8","pl":"węgorz, ser, awokado, mango","ua":"вугор, сир, авокадо, манго","en":"eel, cream cheese, avocado, mango"}', 41),
  (3, 'menu', 'Złoty smok', '55', '{"cat":"rolls","img":"p42","pcs":"8","pl":"łosoś, ser, ogórek, węgorz, sezam, sos unagi","ua":"лосось, сир, огірок, вугор, кунжут, соус унагі","en":"salmon, cream cheese, cucumber, eel, sesame, unagi sauce"}', 42),
  (3, 'menu', 'Philadelphia z krewetkami', '50', '{"cat":"rolls","img":"p43","pcs":"8","pl":"ser, masago, ogórek, krewetki","ua":"сир, масаго, огірок, креветки","en":"cream cheese, masago, cucumber, prawns"}', 43),
  (3, 'menu', 'Philadelphia mango cheddar', '55', '{"cat":"rolls","img":"p44","pcs":"8","pl":"ser, mango, łosoś, cheddar","ua":"сир, манго, лосось, чеддер","en":"cream cheese, mango, salmon, cheddar"}', 44),
  (3, 'menu', 'Fresh futomaki', '30', '{"cat":"rolls","img":"p45","pcs":"8","pl":"łosoś, mango, ogórek","ua":"лосось, манго, огірок","en":"salmon, mango, cucumber"}', 45),
  (3, 'menu', 'Vega futomaki', '25', '{"cat":"rolls","img":"p46","pcs":"8","pl":"batat pieczony, awokado, sos orzechowy","ua":"запечений батат, авокадо, горіховий соус","en":"baked sweet potato, avocado, peanut sauce","veg":true}', 46),
  (3, 'menu', 'Żółty smok z krewetkami', '36', '{"cat":"rolls","img":"p47","pcs":"8","pl":"krewetki, ser, ogórek, mango","ua":"креветки, сир, огірок, манго","en":"prawns, cream cheese, cucumber, mango"}', 47),
  (3, 'menu', 'Żółty smok mix', '40', '{"cat":"rolls","img":"p48","pcs":"8","pl":"łosoś, krewetki, ser, ogórek, kanpyo, mango","ua":"лосось, креветки, сир, огірок, канпьо, манго","en":"salmon, prawns, cream cheese, cucumber, kanpyo, mango"}', 48),
  (3, 'menu', 'Zestaw 100', '450', '{"cat":"sets","img":"p49","pcs":"100","pl":"Philadelphia, zielony smok, łosoś & serek, rolka z krewetkami Pańko, California sake, California krab, California ebi, California unagi, maki kanpyo, unagi maki, ebi maki, sake maki, nigiri z łososiem, węgorzem, tuńczykiem, krewetka","ua":"Філадельфія, зелений смок, лосось & сирок, ролл з креветками Панко, California sake, California краб, California ebi, California unagi, maki kanpyo, unagi maki, ebi maki, sake maki, нігірі з лососем, вугром, тунцем, креветка","en":"Philadelphia, green dragon, salmon & cream cheese, Panko prawn roll, California sake, California crab, California ebi, California unagi, kanpyo maki, unagi maki, ebi maki, sake maki, nigiri with salmon, eel, tuna, prawn"}', 49),
  (3, 'menu', 'Zestaw Łososiowy', '120', '{"cat":"sets","img":"p50","pcs":"26","pl":"Philadelphia, California sake, sake maki, nigiri z łososiem","ua":"Філадельфія, Каліфорнія саке, саке макі, нігірі з лососем","en":"Philadelphia, California sake, sake maki, salmon nigiri"}', 50),
  (3, 'menu', 'Zestaw California', '135', '{"cat":"sets","img":"p51","pcs":"32","pl":"California ebi, California sake, krab California, tuna California","ua":"Каліфорнія ебі, саке, краб та туна","en":"California ebi, sake, krab & tuna"}', 51),
  (3, 'menu', 'Maki trio', '65', '{"cat":"sets","img":"p52","pcs":"24","pl":"sake maki, unagi maki, tuna maki","ua":"саке макі, унагі макі, туна макі","en":"sake maki, unagi maki, tuna maki"}', 52),
  (3, 'menu', 'Zestaw Jesienny', '260', '{"cat":"sets","img":"p53","pcs":"48","pl":"tempura unagi, sake i ebi + rolki na ciepło z węgorzem, krewetkami i łososiem","ua":"темпура унагі, саке та ебі + теплі роли з вугром, креветками й лососем","en":"tempura unagi, sake & ebi + warm rolls with eel, prawns and salmon"}', 53),
  (3, 'menu', 'Philadelphia', '50', '{"cat":"rolls","img":"p54","pcs":"8","pl":"łosoś, ser, ogórek, awokado","ua":"лосось, сир, огірок, авокадо","en":"salmon, cream cheese, cucumber, avocado"}', 54),
  (3, 'menu', 'Philadelphia dorblu', '54', '{"cat":"rolls","img":"p55","pcs":"8","pl":"ser, ogórek, awokado, łosoś opalany, ser dorblu, sos unagi","ua":"сир, огірок, авокадо, обпалений лосось, сир дорблю, соус унагі","en":"cream cheese, cucumber, avocado, seared salmon, dorblu cheese, unagi sauce"}', 55),
  (3, 'menu', 'Zielony smok', '45', '{"cat":"rolls","img":"p56","pcs":"8","pl":"węgorz, daikon, ogórek, ser, awokado, sezam, sos unagi","ua":"вугор, дайкон, огірок, сир, авокадо, кунжут, соус унагі","en":"eel, daikon, cucumber, cream cheese, avocado, sesame, unagi sauce"}', 56),
  (3, 'menu', 'Żółty smok z łososiem', '35', '{"cat":"rolls","img":"p57","pcs":"8","pl":"łosoś, ser, ogórek, mango","ua":"лосось, сир, огірок, манго","en":"salmon, cream cheese, cucumber, mango"}', 57),
  (3, 'menu', 'Burger z łososiem', '60', '{"cat":"burgers","img":"p58","pcs":"1","pl":"łosoś, ser, awokado, ogórek, panierka, sos na wybór","ua":"лосось, сир, авокадо, огірок, паніровка, соус на вибір","en":"salmon, cream cheese, avocado, cucumber, breading, sauce of your choice"}', 58),
  (3, 'menu', 'Burger z krewetkami', '55', '{"cat":"burgers","img":"p59","pcs":"1","pl":"krewetki, ser, ogórek, ser dorblu, panierka, sos na wybór","ua":"креветки, сир, огірок, сир дорблю, паніровка, соус на вибір","en":"prawns, cream cheese, cucumber, dorblu cheese, breading, sauce of your choice"}', 59),
  (3, 'menu', 'Sztos', '65', '{"cat":"burgers","img":"p60","pcs":"1","pl":"krewetki panko, mango, ser, łosoś, ogórek, panierka tempura + sos na wybór","ua":"креветки панко, манго, сир, лосось, огірок, паніровка темпура + соус на вибір","en":"panko prawns, mango, cream cheese, salmon, cucumber, tempura batter + sauce of your choice"}', 60),
  (3, 'menu', 'Buldak roll', '38', '{"cat":"rolls","img":"p61","pcs":"8","pl":"łosoś, ser, ogórek, buldak mayo sos, sezam","ua":"лосось, сир, огірок, соус буldak майо, кунжут","en":"salmon, cream cheese, cucumber, buldak mayo sauce, sesame","spicy":"3"}', 61),
  (3, 'menu', 'Rainbow roll', '53', '{"cat":"rolls","img":"p62","pcs":"8","pl":"węgorz, kanpyo, ser, ogórek, awokado, łosoś, unagi sos","ua":"вугор, канпьо, сир, огірок, авокадо, лосось, соус унагі","en":"eel, kanpyo, cream cheese, cucumber, avocado, salmon, unagi sauce"}', 62),
  (3, 'menu', 'Neon roll', '35', '{"cat":"rolls","img":"p63","pcs":"8","pl":"wakame, łosoś, sos orzechowy, sezam","ua":"вакаме, лосось, горіховий соус, кунжут","en":"wakame, salmon, peanut sauce, sesame"}', 63),
  (3, 'menu', 'Awokado roll', '42', '{"cat":"rolls","img":"p64","pcs":"8","pl":"łosoś, krewetki, mango, awokado, sweet chili mayo","ua":"лосось, креветки, манго, авокадо, sweet chili mayo","en":"salmon, prawns, mango, avocado, sweet chili mayo"}', 64),
  (3, 'menu', 'Sunset', '55', '{"cat":"rolls","img":"p65","pcs":"8","pl":"krewetki pańko, ser, mango, awokado, łosoś, sezam, unagi sos","ua":"креветки панко, сир, манго, авокадо, лосось, кунжут, соус унагі","en":"panko prawns, cream cheese, mango, avocado, salmon, sesame, unagi sauce"}', 65),
  (3, 'menu', 'Zestaw October', '180', '{"cat":"sets","img":"p66","pcs":"32","pl":"łosoś & serek, tempura ebi, zielony smok, Philadelphia","ua":"лосось & сирок, темпура ебі, зелений смок, Філадельфія","en":"salmon & cream cheese, tempura ebi, green dragon, Philadelphia"}', 66),
  (3, 'menu', 'Zestaw 4 smoky', '185', '{"cat":"sets","img":"p67","pcs":"32","pl":"Philadelphia, zielony smok, żółty smok mix, Philadelphia dorblu","ua":"Філадельфія, зелений смок, жовтий смок мікс, Філадельфія дорблю","en":"Philadelphia, green dragon, yellow dragon mix, Philadelphia dorblu"}', 67),
  (3, 'menu', 'Zestaw Amour', '215', '{"cat":"sets","img":"p68","pcs":"40","pl":"Philadelphia, zielony smok, łosoś & serek, California yaki i ebi","ua":"Філадельфія, зелений смок, лосось & сирок, Каліфорнія які та ебі","en":"Philadelphia, green dragon, salmon & cream cheese, California yaki & ebi"}', 68),
  (3, 'menu', 'Zestaw Spring', '210', '{"cat":"sets","img":"p69","pcs":"40","pl":"łosoś & serek, ayame, California mix, gejsza, California unagi","ua":"лосось & сирок, аяме, Каліфорнія мікс, гейша, Каліфорнія унагі","en":"salmon & cream cheese, ayame, California mix, geisha, California unagi"}', 69),
  (3, 'menu', 'Zestaw Tokyo night', '210', '{"cat":"sets","img":"p70","pcs":"36","pl":"uramaki z łososiem (ser, ogórek, łosoś, sweet chilli mayo, jalapeño), uramaki krewetka panko (sezam, mango, krewetki panko, sos unagi), futomaki łosoś-węgorz (łosoś, węgorz, ogórek, sweet chilli mayo, jalapeño), California łosoś (masago, łosoś, awokado), 2× nigiri z łososiem, 2× nigiri z opalanym tuńczykiem i sweet chilli mayo","ua":"урамакі з лососем (сир, огірок, лосось, sweet chilli mayo, халапеньйо), урамакі креветка панко (кунжут, манго, креветки панко, соус унагі), футомакі лосось-вугор (лосось, вугор, огірок, sweet chilli mayo, халапеньйо), California лосось (масаго, лосось, авокадо), 2× нігірі з лососем, 2× нігірі з обпаленим тунцем і sweet chilli mayo","en":"salmon uramaki (cheese, cucumber, salmon, sweet chilli mayo, jalapeño), panko prawn uramaki (sesame, mango, panko prawns, unagi sauce), salmon-eel futomaki (salmon, eel, cucumber, sweet chilli mayo, jalapeño), salmon California (masago, salmon, avocado), 2x salmon nigiri, 2x seared tuna nigiri with sweet chilli mayo"}', 70),
  (3, 'menu', 'Łosoś XL', '53', '{"cat":"rolls","img":"p71","pcs":"8","pl":"ogórek, łosoś, tuńczyk suszony","ua":"огірок, лосось, сушений тунець","en":"cucumber, salmon, dried tuna flakes"}', 71),
  (3, 'menu', 'Golden shark', '52', '{"cat":"rolls","img":"p72","pcs":"8","pl":"mango, ser, tuńczyk, sweet chili mayo, masago, złoto","ua":"манго, сир, тунець, sweet chili mayo, масаго, золото","en":"mango, cream cheese, tuna, sweet chili mayo, masago, edible gold"}', 72),
  (3, 'menu', 'Black ebi', '56', '{"cat":"rolls","img":"p73","pcs":"8","pl":"masago, ser, krewetki, awokado","ua":"масаго, сир, креветки, авокадо","en":"masago, cream cheese, prawns, avocado"}', 73),
  (3, 'menu', 'Unagi Premium', '58', '{"cat":"rolls","img":"p74","pcs":"8","pl":"ogórek, węgorz, sezam","ua":"огірок, вугор, кунжут","en":"cucumber, eel, sesame"}', 74),
  (3, 'menu', 'Zestaw Premium', '215', '{"cat":"sets","img":"p75","pcs":"32","pl":"Łosoś XL, Black Ebi, Golden Shark, Unagi Premium","ua":"Лосось XL, Black Ebi, Golden Shark, Unagi Premium","en":"Salmon XL, Black Ebi, Golden Shark, Unagi Premium"}', 75),
  (3, 'menu', 'Zestaw nr 1', '72', '{"cat":"sets","img":"p76","pcs":"24","pl":"futomaki z kanpyo, ogórkiem i awokado (sos unagi, sezam), California w sezamie z ogórkiem, serkiem i pieczonym łososiem, futomaki z małżami panko, serkiem, ogórkiem i awokado (sweet chilli mayo)","ua":"футомакі з канпьо, огірком та авокадо (соус унагі, кунжут), Каліфорнія в кунжуті з огірком, сирком і запеченим лососем, футомакі з мідіями панко, сирком, огірком та авокадо (sweet chilli mayo)","en":"kanpyo, cucumber & avocado futomaki (unagi sauce, sesame), sesame California with cucumber, cream cheese & baked salmon, panko mussel futomaki with cream cheese, cucumber & avocado (sweet chilli mayo)"}', 76),
  (3, 'menu', 'Zestaw nr 2', '75', '{"cat":"sets","img":"p77","pcs":"32","pl":"maki z ogórkiem, sake maki w tempurze (sweet chilli mayo), California z surimi, ogórkiem i serkiem w masago, futomaki z wędzonym kurczakiem, serkiem i ogórkiem (sos unagi, sweet chilli mayo)","ua":"макі з огірком, саке макі в темпурі (sweet chilli mayo), Каліфорнія з сурімі, огірком і сирком у масаго, футомакі з копченою куркою, сирком та огірком (соус унагі, sweet chilli mayo)","en":"cucumber maki, tempura sake maki (sweet chilli mayo), surimi California with cucumber & cream cheese in masago, smoked chicken futomaki with cream cheese & cucumber (unagi sauce, sweet chilli mayo)"}', 77),
  (3, 'menu', 'Zestaw nr 3', '125', '{"cat":"sets","img":"p78","pcs":"40","pl":"futomaki z łososiem panko, serkiem i ogórkiem (sweet chilli mayo, chrupiąca cebulka), futomaki z ogórkiem, awokado i mango, rolka z krewetką panko, serkiem i ogórkiem (sos unagi, sezam), California z pieczonym łososiem, ogórkiem i serkiem w sezamie, rolka w tempurze z wędzonym kurczakiem, serkiem i ogórkiem (sos teriyaki)","ua":"футомакі з лососем панко, сирком та огірком (sweet chilli mayo, хрустка цибулька), футомакі з огірком, авокадо і манго, рол з креветкою панко, сирком та огірком (соус унагі, кунжут), Каліфорнія із запеченим лососем, огірком і сирком у кунжуті, рол у темпурі з копченою куркою, сирком та огірком (соус теріякі)","en":"panko salmon futomaki with cream cheese & cucumber (sweet chilli mayo, crispy onion), cucumber, avocado & mango futomaki, panko prawn roll with cream cheese & cucumber (unagi sauce, sesame), sesame California with baked salmon, cucumber & cream cheese, tempura roll with smoked chicken, cream cheese & cucumber (teriyaki sauce)"}', 78),
  (3, 'menu', 'Zestaw nr 4', '150', '{"cat":"sets","img":"p79","pcs":"56","pl":"awokado maki, kanpyo maki, rolka w tempurze z wędzonym kurczakiem, serkiem i ogórkiem (teriyaki), rolka z krewetką panko, serkiem i ogórkiem (sos unagi, sezam), California sake, futomaki z małżami panko, serkiem i mango (sos orzechowy), uramaki z krewetką, serkiem i ogórkiem otulone łososiem","ua":"авокадо макі, канпьо макі, рол у темпурі з копченою куркою, сирком та огірком (теріякі), рол з креветкою панко, сирком та огірком (соус унагі, кунжут), Каліфорнія саке, футомакі з мідіями панко, сирком і манго (горіховий соус), урамакі з креветкою, сирком та огірком, огорнуті лососем","en":"avocado maki, kanpyo maki, tempura roll with smoked chicken, cream cheese & cucumber (teriyaki), panko prawn roll with cream cheese & cucumber (unagi sauce, sesame), California sake, panko mussel futomaki with cream cheese & mango (peanut sauce), prawn, cream cheese & cucumber uramaki wrapped in salmon"}', 79),
  (3, 'menu', 'Coca-Cola Zero', '7', '{"cat":"drinks","img":"p80","pcs":"","pl":"zero cukru","ua":"без цукру","en":"sugar free","vol":"0,33 l"}', 80),
  (3, 'menu', 'Fanta', '7', '{"cat":"drinks","img":"p81","pcs":"","pl":"pomarańczowa","ua":"апельсинова","en":"orange","vol":"0,33 l"}', 81),
  (3, 'menu', 'Sprite', '7', '{"cat":"drinks","img":"p82","pcs":"","pl":"cytryna-limonka","ua":"лимон-лайм","en":"lemon-lime","vol":"0,33 l"}', 82),
  (3, 'menu', 'Boba tea Strawberry', '6', '{"cat":"drinks","img":"p83","pcs":"","pl":"czarna herbata, popping boba, truskawka","ua":"чорний чай, кульки boba, полуниця","en":"black tea, popping boba, strawberry","vol":"0,33 l"}', 83),
  (3, 'menu', 'Boba tea Peach', '6', '{"cat":"drinks","img":"p84","pcs":"","pl":"czarna herbata, popping boba, brzoskwinia","ua":"чорний чай, кульки boba, персик","en":"black tea, popping boba, peach","vol":"0,33 l"}', 84),
  (3, 'menu', 'Kombucha Yerba Maté', '15', '{"cat":"drinks","img":"p85","pcs":"","pl":"napój fermentowany, probiotyki","ua":"ферментований напій, пробіотики","en":"fermented drink, probiotics","vol":"0,33 l"}', 85),
  (3, 'menu', 'Woda gazowana', '5', '{"cat":"drinks","img":"p86","pcs":"","pl":"Nałęczowianka, mineralna","ua":"Nałęczowianka, мінеральна","en":"Nałęczowianka sparkling mineral","vol":"0,5 l"}', 86),
  (3, 'menu', 'Woda niegazowana', '5', '{"cat":"drinks","img":"p87","pcs":"","pl":"Nałęczowianka, mineralna","ua":"Nałęczowianka, мінеральна","en":"Nałęczowianka still mineral","vol":"0,5 l"}', 87),
  (3, 'menu', 'Unagi', '3', '{"cat":"sosy","img":"p88","pcs":"1","pl":"słodko-słony na bazie soi","ua":"солодко-солоний на основі сої","en":"sweet & salty soy-based"}', 88),
  (3, 'menu', 'Teriyaki', '3', '{"cat":"sosy","img":"p89","pcs":"1","pl":"klasyczny japoński, słodkawy","ua":"класичний японський, солодкуватий","en":"classic Japanese, slightly sweet"}', 89),
  (3, 'menu', 'Sriracha', '3', '{"cat":"sosy","img":"p90","pcs":"1","pl":"wyrazisty sos chili","ua":"виразний соус чилі","en":"bold chili sauce"}', 90),
  (3, 'menu', 'Słodki chilli', '3', '{"cat":"sosy","img":"p91","pcs":"1","pl":"łagodnie pikantny, słodki","ua":"мʼяко-гострий, солодкий","en":"mildly spicy & sweet"}', 91),
  (3, 'menu', 'Sweet chilli mayo', '3', '{"cat":"sosy","img":"p92","pcs":"1","pl":"kremowy, słodko-pikantny","ua":"кремовий, солодко-гострий","en":"creamy sweet-spicy"}', 92),
  (3, 'menu', 'Orzechowy', '3', '{"cat":"sosy","img":"p93","pcs":"1","pl":"kremowy sos orzechowy","ua":"кремовий горіховий","en":"creamy peanut sauce"}', 93),
  (3, 'menu', 'Sriracha mayo', '3', '{"cat":"sosy","img":"p94","pcs":"1","pl":"kremowy z nutą chili","ua":"кремовий з ноткою чилі","en":"creamy with a chili kick"}', 94),
  (3, 'menu', 'Buldak mayo', '3', '{"cat":"sosy","img":"p95","pcs":"1","pl":"bardzo ostry, koreański","ua":"дуже гострий, корейський","en":"very hot, Korean style","spicy":"2"}', 95),
  (3, 'menu', 'Carolina Reaper mayo', '3', '{"cat":"sosy","img":"p96","pcs":"1","pl":"ekstremalnie ostry","ua":"екстремально гострий","en":"extremely hot","spicy":"3"}', 96),
  (3, 'menu', 'Zestaw Miesiąca | Lipiec', '155', '{"cat":"sets","img":"p97","pcs":"36","pl":"mini burger sushi (surimi, cheddar, ogórek, masago, sos unagi), 2× gunkan wakame (sałatka wakame, sos orzechowy, sezam), 2× gunkan z pieczonym łososiem (sriracha mayo), 8× maki bez ryżu (łosoś, krewetka, serek, ogórek), 8× futomaki (łosoś panko, mango, sweet chili mayo), 8× uramaki w masago (tuńczyk, awokado, serek), 8× hosomaki z marynowanym daikonem + 2 napoje 0,33 l gratis do wyboru (cola, fanta lub sprite)","ua":"міні бургер суші (сурімі, чеддер, огірок, масаго, соус унагі), 2× гункан вакаме (салат вакаме, горіховий соус, кунжут), 2× гункан із запеченим лососем (срірача майо), 8× макі без рису (лосось, креветка, сирок, огірок), 8× футомакі (лосось панко, манго, sweet chili mayo), 8× урамакі в масаго (тунець, авокадо, сирок), 8× хосомакі з маринованим дайконом + 2 напої 0,33 л безкоштовно на вибір (кола, фанта або спрайт)","en":"mini sushi burger (surimi, cheddar, cucumber, masago, unagi sauce), 2× wakame gunkan (wakame salad, peanut sauce, sesame), 2× baked salmon gunkan (sriracha mayo), 8× rice-free maki (salmon, prawn, cream cheese, cucumber), 8× futomaki (panko salmon, mango, sweet chili mayo), 8× masago uramaki (tuna, avocado, cream cheese), 8× pickled daikon hosomaki + 2 free 0.33 l drinks of your choice (cola, fanta or sprite)","vol":"36 szt + burger","promo":true}', 97);
