-- ============================================================
--  ПЛАТФОРМА АДМІНОК arawebsite — схема бази даних
--  Запускається ОДИН раз у новому проєкті Supabase (SQL Editor)
-- ============================================================

-- 1) Сайти-клієнти
create table public.sites (
  id bigint generated by default as identity primary key,
  slug text not null unique,                 -- коротке ім'я: sushiboom
  name text not null,                        -- людська назва: SUSHI BOOM
  paid_until date not null default (current_date + 30),  -- підписка активна до
  config jsonb not null default '{"collections":[],"texts":[]}',
  created_at timestamptz not null default now()
);

-- 2) Хто яким сайтом володіє (роль admin = власник платформи, бачить усе)
create table public.profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  site_id bigint references public.sites (id) on delete set null,
  role text not null default 'owner' check (role in ('owner', 'admin')),
  created_at timestamptz not null default now()
);

-- 3) Картки контенту всіх сайтів (страви, послуги, майстри, категорії…)
create table public.items (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.sites (id) on delete cascade,
  collection text not null,                  -- 'menu', 'cats', 'promo'…
  title text not null default '',
  text text not null default '',
  price text not null default '',
  image_url text not null default '',
  extra jsonb not null default '{}',         -- додаткові поля без зміни схеми
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);
create index items_site_collection on public.items (site_id, collection, sort_order);

-- 4) Прості тексти сайту (телефон, адреса, заголовки)
create table public.texts (
  site_id bigint not null references public.sites (id) on delete cascade,
  key text not null,
  value text not null default '',
  primary key (site_id, key)
);

-- ---------- Допоміжні функції для правил безпеки ----------

create function public.is_admin() returns boolean
language sql stable security definer set search_path = public as
$$ select exists (select 1 from profiles where user_id = auth.uid() and role = 'admin') $$;

create function public.my_site() returns bigint
language sql stable security definer set search_path = public as
$$ select site_id from profiles where user_id = auth.uid() $$;

-- Підписка сайту активна?
create function public.site_paid(sid bigint) returns boolean
language sql stable security definer set search_path = public as
$$ select exists (select 1 from sites where id = sid and paid_until >= current_date) $$;

-- ---------- Правила безпеки (RLS) ----------

alter table public.sites enable row level security;
alter table public.profiles enable row level security;
alter table public.items enable row level security;
alter table public.texts enable row level security;

-- sites: власник бачить свій сайт, admin — усі; змінює лише admin
create policy "sites read" on public.sites
  for select to authenticated using (is_admin() or id = my_site());
create policy "sites admin insert" on public.sites
  for insert to authenticated with check (is_admin());
create policy "sites admin update" on public.sites
  for update to authenticated using (is_admin()) with check (is_admin());
create policy "sites admin delete" on public.sites
  for delete to authenticated using (is_admin());

-- profiles: кожен бачить свій профіль, admin — усі; змінює лише admin
create policy "profiles read" on public.profiles
  for select to authenticated using (user_id = auth.uid() or is_admin());
create policy "profiles admin insert" on public.profiles
  for insert to authenticated with check (is_admin());
create policy "profiles admin update" on public.profiles
  for update to authenticated using (is_admin()) with check (is_admin());
create policy "profiles admin delete" on public.profiles
  for delete to authenticated using (is_admin());

-- items: читають УСІ (публічні сайти тягнуть контент анонімно);
-- пишуть admin або власник свого сайту З АКТИВНОЮ ПІДПИСКОЮ
create policy "items public read" on public.items
  for select using (true);
create policy "items owner insert" on public.items
  for insert to authenticated
  with check (is_admin() or (site_id = my_site() and site_paid(site_id)));
create policy "items owner update" on public.items
  for update to authenticated
  using (is_admin() or (site_id = my_site() and site_paid(site_id)))
  with check (is_admin() or (site_id = my_site() and site_paid(site_id)));
create policy "items owner delete" on public.items
  for delete to authenticated
  using (is_admin() or (site_id = my_site() and site_paid(site_id)));

-- texts: ті самі правила, що для items
create policy "texts public read" on public.texts
  for select using (true);
create policy "texts owner insert" on public.texts
  for insert to authenticated
  with check (is_admin() or (site_id = my_site() and site_paid(site_id)));
create policy "texts owner update" on public.texts
  for update to authenticated
  using (is_admin() or (site_id = my_site() and site_paid(site_id)))
  with check (is_admin() or (site_id = my_site() and site_paid(site_id)));
create policy "texts owner delete" on public.texts
  for delete to authenticated
  using (is_admin() or (site_id = my_site() and site_paid(site_id)));

-- ---------- Сховище для фото ----------

insert into storage.buckets (id, name, public) values ('site-images', 'site-images', true);

create policy "site images public read" on storage.objects
  for select using (bucket_id = 'site-images');
create policy "site images auth insert" on storage.objects
  for insert to authenticated with check (bucket_id = 'site-images');
create policy "site images auth update" on storage.objects
  for update to authenticated using (bucket_id = 'site-images');
create policy "site images auth delete" on storage.objects
  for delete to authenticated using (bucket_id = 'site-images');

-- ============================================================
--  ПІЛОТ: сайт SUSHI BOOM (точка Царичанка) з реальним меню
--  (у свіжій базі цей сайт отримає id = 1)
-- ============================================================

insert into public.sites (slug, name, paid_until, config) values (
  'sushiboom',
  'SUSHI BOOM',
  current_date + 365,
  '{
    "collections": [
      {
        "key": "cats",
        "name": "Категорії меню",
        "fields": [
          {"key": "title", "name": "Назва категорії", "type": "text"},
          {"key": "catkey", "name": "Код (латиницею, не міняти)", "type": "text", "extra": true}
        ]
      },
      {
        "key": "menu",
        "name": "Меню",
        "fields": [
          {"key": "title", "name": "Назва", "type": "text"},
          {"key": "text", "name": "Склад", "type": "textarea"},
          {"key": "price", "name": "Ціна, грн", "type": "text"},
          {"key": "image", "name": "Фото", "type": "image"},
          {"key": "cat", "name": "Категорія", "type": "select-collection", "from": "cats", "extra": true},
          {"key": "top", "name": "Хіт продажів", "type": "checkbox", "extra": true},
          {"key": "unit", "name": "Кількість (для сетів)", "type": "text", "extra": true}
        ]
      }
    ],
    "texts": [
      {"key": "phone", "name": "Телефон"},
      {"key": "address", "name": "Адреса"}
    ]
  }'
);

-- Категорії
insert into public.items (site_id, collection, title, extra, sort_order) values
  (1, 'cats', 'Філадельфія',  '{"catkey":"phil"}',    1),
  (1, 'cats', 'Каліфорнія',   '{"catkey":"cal"}',     2),
  (1, 'cats', 'Макі',         '{"catkey":"maki"}',    3),
  (1, 'cats', 'Темпура',      '{"catkey":"tempura"}', 4),
  (1, 'cats', 'Суші-бургери', '{"catkey":"burger"}',  5),
  (1, 'cats', 'Сети',         '{"catkey":"sets"}',    6);

-- Страви (меню Царичанки)
insert into public.items (site_id, collection, title, text, price, extra, sort_order) values
  (1, 'menu', 'Філадельфія класік',           'Рис, норі, крем сир, огірок, авокадо, лосось',                          '350', '{"cat":"phil","img":"phil_klasik","top":true}', 1),
  (1, 'menu', 'Філадельфія тунець',           'Рис, норі, крем сир, огірок, авокадо, тунець, соус унагі',              '300', '{"cat":"phil","img":"phil_tunec"}', 2),
  (1, 'menu', 'Філадельфія з вугрем',         'Рис, норі, крем сир, огірок, авокадо, вугор, соус унагі, кунжут',       '360', '{"cat":"phil","img":"phil_vugor"}', 3),
  (1, 'menu', 'Філадельфія креветка',         'Рис, норі, крем сир, огірок, авокадо, креветка',                        '340', '{"cat":"phil","img":"phil_krevetka"}', 4),
  (1, 'menu', 'Мальдіви',                     'Рис, норі, крем сир, авокадо, огірок, сир чедер',                       '380', '{"cat":"phil","img":"maldivy","top":true}', 5),
  (1, 'menu', 'Філадельфія краб в ікрі',      'Рис, норі, крем сир, сніжний краб, ікра тобіко',                        '260', '{"cat":"phil","img":"phil_krab_ikra"}', 6),
  (1, 'menu', 'Філадельфія тунець в кунжуті', 'Рис, норі, крем сир, огірок, тунець, кунжут',                           '320', '{"cat":"phil","img":"phil_tunec_kunzhut"}', 7),
  (1, 'menu', 'Філадельфія лосось в ікрі',    'Рис, норі, авокадо, огірок, лосось, ікра тобіко',                       '320', '{"cat":"phil","img":"phil_losos_ikra"}', 8),
  (1, 'menu', 'Філадельфія лосось в кунжуті', 'Рис, норі, крем сир, огірок, лосось, кунжут',                           '320', '{"cat":"phil","img":"phil_losos_kunzhut"}', 9),
  (1, 'menu', 'Філадельфія тунець в ікрі',    'Рис, норі, крем сир, тунець, огірок, ікра тобіко',                      '300', '{"cat":"phil","img":"phil_tunec_ikra"}', 10),
  (1, 'menu', 'Каліфорнія лосось в ікрі',     'Рис, норі, авокадо, огірок, лосось, ікра тобіко',                       '300', '{"cat":"cal","img":"cal_losos_ikra"}', 11),
  (1, 'menu', 'Каліфорнія в кунжуті',         'Рис, норі, огірок, авокадо, лосось, кунжут',                            '300', '{"cat":"cal","img":"cal_kunzhut"}', 12),
  (1, 'menu', 'Каліфорнія тунець в ікрі',     'Рис, норі, огірок, авокадо, тунець, ікра тобіко',                       '300', '{"cat":"cal","img":"cal_tunec_ikra"}', 13),
  (1, 'menu', 'Каліфорнія тунець в кунжуті',  'Рис, норі, тунець, огірок, авокадо',                                    '300', '{"cat":"cal","img":"cal_tunec_kunzhut"}', 14),
  (1, 'menu', 'Сирний рол',                   'Рис, норі, крем сир, сир чедер, соус унагі',                            '280', '{"cat":"cal","img":"syrnyi_rol"}', 15),
  (1, 'menu', 'Макі з огірком',               'Рис, норі, огірок',                                                     '150', '{"cat":"maki","img":"maki_ogirok"}', 16),
  (1, 'menu', 'Макі з тунцем',                'Рис, норі, тунець',                                                     '200', '{"cat":"maki","img":"maki_tunec"}', 17),
  (1, 'menu', 'Макі з креветкою',             'Рис, норі, креветка',                                                   '220', '{"cat":"maki","img":"maki_krevetka"}', 18),
  (1, 'menu', 'Макі з лососем',               'Рис, норі, лосось',                                                     '220', '{"cat":"maki","img":"maki_losos"}', 19),
  (1, 'menu', 'Макі з вугрем',                'Рис, норі, вугор, кунжут, соус унагі',                                  '240', '{"cat":"maki","img":"maki_vugor"}', 20),
  (1, 'menu', 'Темпура з лососем',            'Рис, норі, крем сир, лосось, авокадо, кляр, сухарі панко, соус унагі',  '350', '{"cat":"tempura","img":"tempura_losos"}', 21),
  (1, 'menu', 'Темпура з тунцем',             'Рис, норі, крем сир, цибуля зелена, тунець, сир чедер, кляр, сухарі панко, соус', '330', '{"cat":"tempura","img":"tempura_tunec"}', 22),
  (1, 'menu', 'Темпура з креветкою',          'Рис, норі, крем сир, креветка, сир чедер, кляр, сухарі панко, соус теріякі',      '350', '{"cat":"tempura","img":"tempura_krevetka"}', 23),
  (1, 'menu', 'Суші бургер з креветкою',      'Рис, норі, крем сир, помідор, креветка, авокадо, моцарела, соус солодкий чілі, кляр, сухарі панко', '360', '{"cat":"burger","img":"burger_krevetka"}', 24),
  (1, 'menu', 'Суші бургер з лососем',        'Рис, норі, крем сир, помідор, лосось, авокадо, моцарела, соус унагі, кляр, сухарі панко',           '360', '{"cat":"burger","img":"burger_losos","top":true}', 25),
  (1, 'menu', 'Суші бургер з тунцем',         'Рис, норі, крем сир, помідор, тунець, авокадо, моцарела, соус теріякі, кляр, сухарі панко',         '360', '{"cat":"burger","img":"burger_tunec"}', 26),
  (1, 'menu', 'Сет Макі',                     'Макі краб · Макі огірок · Макі креветка · Макі тунець · Макі лосось',   '900',  '{"cat":"sets","img":"set_maki","unit":"40 шт"}', 27),
  (1, 'menu', 'Сет MiniBoom',                 'Філадельфія краб в ікрі · Філадельфія тунець в стружці тунця · Макі креветка', '770', '{"cat":"sets","img":"set_miniboom","unit":"24 шт"}', 28),
  (1, 'menu', 'Сет GoodBoom',                 'Філадельфія лосось в кунжуті · Філадельфія краб в ікрі · Філадельфія тунець в стружці тунця · Макі лосось · Макі огірок', '1200', '{"cat":"sets","img":"set_goodboom","unit":"40 шт","top":true}', 29),
  (1, 'menu', 'Сет SuperBoom',                'Філадельфія лосось в кунжуті · Філадельфія краб в ікрі · Філадельфія тунець в стружці тунця · Сирний рол · Макі лосось · Макі огірок', '1500', '{"cat":"sets","img":"set_superboom","unit":"48 шт"}', 30);

-- ============================================================
--  ПІСЛЯ створення користувачів у Authentication → Users
--  виконати окремо (підставивши справжні email):
--
--  -- ваш акаунт власника платформи (бачить і редагує все):
--  insert into public.profiles (user_id, site_id, role)
--  select id, null, 'admin' from auth.users where email = 'arikpro92@gmail.com';
--
--  -- акаунт власника SUSHI BOOM (бачить лише свій сайт):
--  insert into public.profiles (user_id, site_id, role)
--  select id, 1, 'owner' from auth.users where email = 'EMAIL_ВЛАСНИКА';
-- ============================================================
